name: sentinel_hub
description: "Sistema de monitoramento e automação Sentinel-Hub"
publish_to: 'none'

version: 1.0.7+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # --- ÚLITILITÁRIOS BASE ---
  shared_preferences: ^2.2.2
  http: ^1.6.0
  url_launcher: ^6.3.2
  uuid: ^4.6.0
  
  # --- PROCESSAMENTO DE VÍDEO NATIVO (RTSP) ---
  media_kit: ^1.1.10
  media_kit_video: ^1.2.5
  media_kit_libs_linux: ^1.0.4
  media_kit_libs_android_video: ^1.0.4
  media_kit_libs_ios_video: ^1.0.4
  media_kit_libs_windows_video: ^1.0.4
  
  # --- NOTIFICAÇÕES LOCAIS E ISOLAMENTO ---
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^17.2.4
  universal_platform: ^1.1.0
  package_info_plus: ^10.2.1
  open_filex: ^4.7.0
  path_provider: ^2.1.6
  dio: ^5.11.0
  web_socket_channel: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  audio_video_progress_bar: ^2.0.0

flutter:
  uses-material-design: true