name: sentinel_hub
description: "Sistema de monitoramento e automação Sentinel-Hub"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  http: ^1.2.1
  media_kit: ^1.1.10
  media_kit_video: ^1.2.5
  media_kit_libs_linux: ^1.0.4
  url_launcher: ^6.3.2
  uuid: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  audio_video_progress_bar: ^2.0.0

flutter:
  uses-material-design: true