name: sentinel_hub
description: "Sistema de monitoramento e automação Sentinel-Hub"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # --- ÚLITILITÁRIOS BASE ---
  shared_preferences: ^2.2.2
  http: ^1.2.1
  url_launcher: ^6.3.2
  uuid: ^4.6.0
  
  # --- PROCESSAMENTO DE VÍDEO NATIVO (RTSP) ---
  media_kit: ^1.1.10
  media_kit_video: ^1.2.5
  media_kit_libs_linux: ^1.0.4
  media_kit_libs_android_video: ^1.0.4
  media_kit_libs_ios_video: ^1.0.4
  media_kit_libs_windows_video: ^1.0.4 # <- Garante a libmpv-2.dll e dependências no Windows
  
# --- NOTIFICAÇÕES LOCAIS E ISOLAMENTO (NOVO PLANO) ---
  flutter_background_service: ^3.0.0     # Mantém o app a ouvir a rede em segundo plano
  flutter_local_notifications: ^17.0.0   # Gera o alerta visual/sonoro no telemóvel
  universal_platform: ^1.1.0
  # (Adeus eventsource, não precisamos de ti!)                  # Lê o protocolo SSE do ntfy.sh em tempo real

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
dependency_overrides:
  audio_video_progress_bar: ^2.0.0

flutter:
  uses-material-design: true