// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl6FbnSTGfU5k6GszcjUi8a-C4870U5Lk',
    appId: '1:507640624956:android:d76e727333834f9cb05039',
    messagingSenderId: '507640624956',
    projectId: 'ktsentinel-aa307',
    storageBucket: 'ktsentinel-aa307.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfx28o_KwQuP6IhPz0ESh7bPYpCfGvIy0',
    appId: '1:507640624956:ios:e2579e53c042081db05039',
    messagingSenderId: '507640624956',
    projectId: 'ktsentinel-aa307',
    storageBucket: 'ktsentinel-aa307.firebasestorage.app',
    iosBundleId: 'com.example.sentinelHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfx28o_KwQuP6IhPz0ESh7bPYpCfGvIy0',
    appId: '1:507640624956:ios:e2579e53c042081db05039',
    messagingSenderId: '507640624956',
    projectId: 'ktsentinel-aa307',
    storageBucket: 'ktsentinel-aa307.firebasestorage.app',
    iosBundleId: 'com.example.sentinelHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQJkTRFnbmuZA90iWY879SyDLQPPtq2qY',
    appId: '1:507640624956:web:aff767b7394e81bbb05039',
    messagingSenderId: '507640624956',
    projectId: 'ktsentinel-aa307',
    authDomain: 'ktsentinel-aa307.firebaseapp.com',
    storageBucket: 'ktsentinel-aa307.firebasestorage.app',
  );
}
