import 'package:flutter/material.dart';
import 'package:sentinel_hub/config/app_config.dart';
import 'package:sentinel_hub/models/hardware_module.dart';
import 'package:sentinel_hub/services/module_service.dart';

class ModuleEditScreen extends StatefulWidget {
  final HardwareModule? module;

  const ModuleEditScreen({super.key, this.module});

  @override
  State<ModuleEditScreen> createState() => _ModuleEditScreenState();
}

class _ModuleEditScreenState extends State<ModuleEditScreen> {
  final _formKey = GlobalKey<FormState>();
  final _moduleService = ModuleService();

  late TextEditingController _nameController;
  late TextEditingController _ipController;
  late TextEditingController _rfCodeController;
  late TextEditingController _rfProtocolController;

  ModuleType _selectedModuleType = ModuleType.genericEsp32;

  @override
  void initState() {
    super.initState();
    final module = widget.module;
    _nameController = TextEditingController(text: module?.name ?? '');
    _ipController = TextEditingController(text: module?.ipAddress ?? '');

    _selectedModuleType = module?.type ?? ModuleType.genericEsp32;

    // Initialize controllers for specific settings
    final specificSettings = module?.specificSettings ?? {};
    _rfCodeController =
        TextEditingController(text: specificSettings['rfCode'] ?? '');
    _rfProtocolController =
        TextEditingController(text: specificSettings['rfProtocol'] ?? '6');
  }

  @override
  void dispose() {
    _nameController.dispose();
    _ipController.dispose();
    _rfCodeController.dispose();
    _rfProtocolController.dispose();
    super.dispose();
  }

  String? _validateIpAddress(String? value) {
    if (value == null || value.isEmpty) {
      return 'O endereço IP não pode ser vazio.';
    }
    final ipRegex = RegExp(
        r'^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$');
    if (!ipRegex.hasMatch(value)) {
      return 'Formato de endereço IP inválido.';
    }
    return null;
  }

  String? _validateNotEmpty(String? value) {
    if (value == null || value.isEmpty) {
      return 'Este campo não pode ser vazio.';
    }
    return null;
  }

  Future<void> _saveModule() async {
    if (!_formKey.currentState!.validate()) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
            content: const Text('Por favor, corrija os erros no formulário.'),
            backgroundColor: AppConfig.accentColor.withOpacity(0.14),
            behavior: SnackBarBehavior.floating),
      );
      return;
    }

    try {
      final specificSettings = <String, dynamic>{};
      if (_selectedModuleType == ModuleType.wt32Eth01) {
        specificSettings['rfCode'] = _rfCodeController.text;
        specificSettings['rfProtocol'] = _rfProtocolController.text;
      }

      final moduleData = HardwareModule(
        id: widget.module?.id ?? '', // ID will be generated by service if new
        name: _nameController.text,
        ipAddress: _ipController.text,
        type: _selectedModuleType,
        specificSettings: specificSettings,
      );

      if (widget.module == null) {
        await _moduleService.addModule(moduleData);
      } else {
        await _moduleService.updateModule(moduleData);
      }

      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
            content: const Text('Módulo salvo com sucesso!'),
            backgroundColor: AppConfig.accentColor.withOpacity(0.16),
            behavior: SnackBarBehavior.floating),
      );
      Navigator.of(context).pop(true);
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
            content: Text('Erro ao salvar módulo: $e'),
            backgroundColor: AppConfig.alertColor.withOpacity(0.16),
            behavior: SnackBarBehavior.floating),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title:
            Text(widget.module == null ? 'Adicionar Módulo' : 'Editar Módulo'),
        actions: [
          IconButton(
            icon: const Icon(Icons.save),
            onPressed: _saveModule,
            tooltip: 'Salvar Módulo',
          ),
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              Text('Informações Gerais',
                  style: Theme.of(context).textTheme.titleLarge),
              const SizedBox(height: 16),
              TextFormField(
                controller: _nameController,
                decoration: const InputDecoration(
                    labelText: 'Nome/Identificador do Módulo'),
                validator: _validateNotEmpty,
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _ipController,
                decoration: const InputDecoration(labelText: 'Endereço IP'),
                validator: _validateIpAddress,
                keyboardType: TextInputType.number,
              ),
              const SizedBox(height: 16),
              DropdownButtonFormField<ModuleType>(
                initialValue: _selectedModuleType,
                decoration: const InputDecoration(labelText: 'Tipo de Módulo'),
                items: ModuleType.values.map((type) {
                  return DropdownMenuItem(
                    value: type,
                    child: Text(type.displayName),
                  );
                }).toList(),
                onChanged: (type) {
                  if (type != null) {
                    setState(() {
                      _selectedModuleType = type;
                    });
                  }
                },
              ),
              const SizedBox(height: 24),
              const Divider(),
              const SizedBox(height: 16),
              ..._buildSpecificSettingsFields(),
            ],
          ),
        ),
      ),
    );
  }

  List<Widget> _buildSpecificSettingsFields() {
    if (_selectedModuleType == ModuleType.wt32Eth01 ||
        _selectedModuleType == ModuleType.rfGateway) {
      return [
        Text('Configurações Específicas',
            style: Theme.of(context).textTheme.titleLarge),
        const SizedBox(height: 16),
        TextFormField(
          controller: _rfCodeController,
          decoration:
              const InputDecoration(labelText: 'Código RF da Campainha'),
          keyboardType: TextInputType.number,
          validator: _validateNotEmpty,
        ),
        const SizedBox(height: 16),
        TextFormField(
          controller: _rfProtocolController,
          decoration: const InputDecoration(labelText: 'Protocolo RF'),
          keyboardType: TextInputType.number,
          validator: _validateNotEmpty,
        ),
      ];
    }
    // Return empty list if no specific settings for the selected type
    return [];
  }
}
