name: Build Windows

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Build Windows
      run: flutter build windows --release

    # Compacta a pasta Release num arquivo .zip usando PowerShell
    - name: Compress Build
      run: Compress-Archive -Path build\windows\x64\runner\Release\* -DestinationPath sentinel_hub_windows_x64.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sentinel-hub-windows
        path: sentinel_hub_windows_x64.zip

    # Atualiza a mesma release "latest" com o arquivo Windows
    - name: Automatic Latest Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        files: sentinel_hub_windows_x64.zip
        make_latest: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}