name: Build Android (APK)

on:
  push:
    tags:
      - 'v*' # Dispara a build SOMENTE quando você enviar uma tag, ex: git push origin v1.0.5
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Rename APK
      run: mv build/app/outputs/flutter-apk/app-release.apk sentinel_hub_android.apk

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sentinel-hub-apk
        path: sentinel_hub_android.apk

    - name: Automatic Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }} # Pega dinamicamente o nome da tag (ex: v1.0.5)
        name: "Release ${{ github.ref_name }}"
        body: "Versão atualizada automaticamente via GitHub Actions."
        files: sentinel_hub_android.apk
        make_latest: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}