name: Build Windows (.exe)

on:
  push:
    tags:
      - 'v*' # Dispara a build SOMENTE quando você enviar uma tag, ex: git push origin v1.0.7
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Enable Desktop Support
      run: flutter config --enable-windows-desktop

    - name: Build Windows
      run: flutter build windows --release

    - name: Compress Build
      run: Compress-Archive -Path build\windows\x64\runner\Release\* -DestinationPath sentinel_hub_windows_x64.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sentinel-hub-windows
        path: sentinel_hub_windows_x64.zip

    - name: Automatic Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }} # Pega dinamicamente o nome da tag (ex: v1.0.7)
        name: "Release ${{ github.ref_name }}"
        body: "Versão Windows atualizada automaticamente via GitHub Actions."
        files: sentinel_hub_windows_x64.zip
        make_latest: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}